# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  IDENTIFY-ADALM2000-AFTER-BUILD:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Create the build folder
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    # Configure cmake options 
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DENABLE_PYTHON=off -DENABLE_CSHARP=off -DENABLE_TOOLS=on
    
    # Build libm2k
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .
    
    # Lets make that led blink
    - name: Identify ADALM200 Device
      working-directory: ${{runner.workspace}}/build/tools/m2kcli
      shell: bash
      run: ./m2kcli --identify "usb:1.3.5"
